AppRegistroEstudiantes/Models/Horario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AppRegistroEstudiantes.Models
{
    public class Horario
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Dia { get; set; }
        [DisplayName("Hora Inicio")]
        public string HoraInicio { get; set; }
        [DisplayName("Hora Fin")]
        public string HoraFin { get; set; }
    }
}

AppRegistroEstudiantes/Controllers/HorarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRegistroEstudiantes.Models;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class HorarioController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Horario
        public ActionResult Index()
        {
            return View(db.Horario.ToList());
        }

        // GET: Horario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
            if (horario == null)
            {
                return HttpNotFound();
            }
            return View(horario);
        }

        // GET: Horario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Horario/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Dia,HoraInicio,HoraFin")] Horario horario)
        {
            if (ModelState.IsValid)
            {
                db.Horario.Add(horario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(horario);
        }

        // GET: Horario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
            if (horario == null)
            {
                return HttpNotFound();
            }
            return View(horario);
        }

        // POST: Horario/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Dia,HoraInicio,HoraFin")] Horario horario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(horario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(horario);
        }

        // GET: Horario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
            if (horario == null)
            {
                return HttpNotFound();
            }
            return View(horario);
        }

        // POST: Horario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Horario horario = db.Horario.Find(id);
            db.Horario.Remove(horario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppRegistroEstudiantes/Views/Horario/Create.cshtml
@model AppRegistroEstudiantes.Models.Horario

@{
    ViewBag.Title = "Horario - Nuevo";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formCreateHorario" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Crear Nuevo Horario</h4>
        <hr />
        <div class="card">
            <div class="card-header">
                @Html.ActionLink("Volver Atrás", "Index", "Horario", null, new { @class = "btn btn-secondary" })
                <input id="btnGuardar" type="submit" value="Guardar" class="btn btn-primary" />
            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Dia, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Dia, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dia, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.HoraInicio, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
                        @Html.ValidationMessageFor(model => model.HoraInicio, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.HoraFin, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.HoraFin, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
                        @Html.ValidationMessageFor(model => model.HoraFin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppRegistroEstudiantes/Views/Horario/Delete.cshtml
@model AppRegistroEstudiantes.Models.Horario

@{
    ViewBag.Title = "Horario - Eliminar";
}

<div>
    <h4>¿Estas seguro que quieres eliminar el Horario con Id @Model.Id?</h4>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Dia)</label>
                <div>@Html.DisplayFor(model => model.Dia)</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.HoraInicio)</label>
                <div>@Html.DisplayFor(model => model.HoraInicio)</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.HoraFin)</label>
                <div>@Html.DisplayFor(model => model.HoraFin)</div>
            </div>
        </div>
    </div> 

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Volver Atrás", "Index") |
            <input id="btnEliminar" type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    }
</div>

AppRegistroEstudiantes/Views/Horario/Details.cshtml
@model AppRegistroEstudiantes.Models.Horario

@{
    ViewBag.Title = "Horario - Detalles";
}

<div>
    <h4>Horario Id: @Model.Id</h4>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Dia)</label>
                <div>@Html.DisplayFor(model => model.Dia)</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.HoraInicio)</label>
                <div>@Html.DisplayFor(model => model.HoraInicio)</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.HoraFin)</label>
                <div>@Html.DisplayFor(model => model.HoraFin)</div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Volver Atrás", "Index") |
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
</p>

AppRegistroEstudiantes/Views/Horario/Edit.cshtml
@model AppRegistroEstudiantes.Models.Horario

@{
    ViewBag.Title = "Horario - Editar";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formEditHorario" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Horario</h4>
        <hr />
        <div class="card">
            <div class="card-header">
                @Html.ActionLink("Volver Atrás", "Index", "Horario", null, new { @class = "btn btn-secondary mr-1" })
                <input id="btnActualizar" type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Dia, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Dia, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dia, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.HoraInicio, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
                        @Html.ValidationMessageFor(model => model.HoraInicio, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.HoraFin, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.HoraFin, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
                        @Html.ValidationMessageFor(model => model.HoraFin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppRegistroEstudiantes/Views/Horario/Index.cshtml
@model IEnumerable<AppRegistroEstudiantes.Models.Horario>

@{
    ViewBag.Title = "Horario";
}

<h4>Lista de Horarios</h4>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table" id="tablaHorarios">
    <tr>
        <th width="4%"></th>
        <th width="4%"></th>
        <th width="4%"></th>
        <th>
            @Html.DisplayNameFor(model => model.Dia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraFin)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@Url.Action("Edit", new { id = item.Id })" class="text-secondary" title="Editar">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                </svg>
            </a>
        </td>
        <td>
            <a href="@Url.Action("Details", new { id = item.Id })" class="text-primary" title="Ver">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                </svg>
            </a>
        </td>
        <td>
            <a href="@Url.Action("Delete", new { id = item.Id })" class="text-danger" title="Eliminar">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                </svg>
            </a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoraInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoraFin)
        </td>
    </tr>
}

</table>