AppRegistroEstudiantes/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRegistroEstudiantes.Models;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class AlumnoController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Alumno
        public ActionResult Index()
        {
            var alumnos = db.Alumno.Include(a => a.Madre).Include(a => a.Padre);
            return View(alumnos.ToList());
        }

        // GET: Alumno/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // GET: Alumno/Create
        public ActionResult Create()
        {
            ViewBag.MadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Mujer), "Id", "NombreCompleto");
            ViewBag.PadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Hombre), "Id", "NombreCompleto");
            return View();
        }

        // POST: Alumno/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Genero,CI,FechaNacimiento,LugarNacimiento,Direccion,Zona,Telefono,Foto,Procedencia,PadreID,MadreID")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase Imagen = Request.Files["Foto"];
                if (Imagen != null)
                {
                    string fileType = Path.GetExtension(Imagen.FileName);
                    string fileName = DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + fileType;
                    string path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    alumno.Foto = fileName;
                    Imagen.SaveAs(path);
                    db.Alumno.Add(alumno);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.MadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Mujer), "Id", "NombreCompleto");
            ViewBag.PadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Hombre), "Id", "NombreCompleto");
            return View(alumno);
        }

        // GET: Alumno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            ViewBag.MadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Mujer), "Id", "NombreCompleto", alumno.MadreID);
            ViewBag.PadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Hombre), "Id", "NombreCompleto", alumno.PadreID);
            return View(alumno);
        }

        // POST: Alumno/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Genero,CI,FechaNacimiento,LugarNacimiento,Direccion,Zona,Telefono,Foto,Procedencia,PadreID,MadreID")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase Imagen = Request.Files["FotoUpdated"];
                if (Imagen != null && Imagen.FileName != "")
                {
                    string fileType = Path.GetExtension(Imagen.FileName);
                    string fileName = DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + fileType;
                    string oldImage = Path.Combine(Server.MapPath("~/Content/Images"), alumno.Foto);
                    string newImage = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    alumno.Foto = fileName;
                    Imagen.SaveAs(newImage);
                    if (System.IO.File.Exists(oldImage))
                    {
                        System.IO.File.Delete(oldImage);
                    }
                    
                }
                db.Entry(alumno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Mujer), "Id", "NombreCompleto", alumno.MadreID);
            ViewBag.PadreID = new SelectList(db.Tutor.Where(s => s.Genero == Persona.TipoGenero.Hombre), "Id", "NombreCompleto", alumno.PadreID);
            return View(alumno);
        }

        // GET: Alumno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // POST: Alumno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alumno alumno = db.Alumno.Find(id);
            string rutaImagen = Path.Combine(Server.MapPath("~/Content/Images"), alumno.Foto);
            db.Alumno.Remove(alumno);
            if (System.IO.File.Exists(rutaImagen))
            {
                System.IO.File.Delete(rutaImagen);
            }
            //
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppRegistroEstudiantes/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRegistroEstudiantes.Models;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class CursoController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Curso
        public ActionResult Index()
        {
            return View(db.Curso.ToList());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Curso/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Descripcion")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Curso.Add(curso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(curso);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Descripcion")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Curso curso = db.Curso.Find(id);
            db.Curso.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppRegistroEstudiantes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class HomeController : Controller
    {
        private SchoolContext db = new SchoolContext();

        public ActionResult Index()
        {
            dynamic Response = new ExpandoObject();

            int[] Registros = {
                db.Curso.ToList().Count(),
                db.Tutor.ToList().Count(),
                db.Registro.ToList().Count(),
                db.Alumno.ToList().Count(),
            };
            var ultimasInscripciones= db.Registro.OrderByDescending(s => s.Id).Take(5).ToList();
            Response.Registros = Registros;
            Response.Inscripciones = ultimasInscripciones;

            return View(Response);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return RedirectToAction("Create", "Contacto");
        }
    }
}

AppRegistroEstudiantes/Controllers/TutorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRegistroEstudiantes.Models;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class TutorController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Tutor
        public ActionResult Index()
        {
            // return View(db.Personas.ToList());
            return View(db.Tutor.ToList());
        }

        // GET: Tutor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutor.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            return View(tutor);
        }

        // GET: Tutor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tutor/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Genero,CI,FechaNacimiento,LugarNacimiento,Direccion,Zona,Telefono,Ocupacion")] Tutor tutor)
        {
            if (ModelState.IsValid)
            {
                db.Tutor.Add(tutor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tutor);
        }

        // GET: Tutor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutor.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            return View(tutor);
        }

        // POST: Tutor/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,ApellidoPaterno,ApellidoMaterno,Genero,CI,FechaNacimiento,LugarNacimiento,Direccion,Zona,Telefono,Ocupacion")] Tutor tutor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tutor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tutor);
        }

        // GET: Tutor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutor.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            return View(tutor);
        }

        // POST: Tutor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tutor tutor = db.Tutor.Find(id);
            db.Tutor.Remove(tutor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppRegistroEstudiantes/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppRegistroEstudiantes/Views/Home/Contact.cshtml
@* Esta vista no se usará por el momento *@

AppRegistroEstudiantes/Views/Home/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Menu Principal";
}
<div id="homeCarousel" class="carousel slide carouselCustomHeight mx-n2 mt-n4" data-ride="carousel">
    <div class="carousel-inner carouselCustomHeight">
        @{int i = 0;}
        @foreach (var item in Model.Inscripciones)
        {
            if (i == 0)
            {
                <div class="carousel-item active">
                    <img src="/Content/Images/@item.Alumno.Foto" class="carouselCustomHeight w-100 img-fluid">
                    <div class="carousel-caption d-none d-md-block">
                        <h5 class="text-dark">@item.Alumno.NombreCompleto</h5>
                        <p class="text-dark">Inscrito el: @item.FechaInscripcion.ToString("dd'/'MM'/'yyyy")</p>
                    </div>
                </div>
            }
            else
            {
                <div class="carousel-item">
                    <img src="/Content/Images/@item.Alumno.Foto" class="carouselCustomHeight w-100 img-fluid">
                    <div class="carousel-caption d-none d-md-block">
                        <h5 class="text-dark">@item.Alumno.NombreCompleto</h5>
                        <p class="text-dark">Inscrito el: @item.FechaInscripcion.ToString("dd'/'MM'/'yyyy")</p>
                    </div>
                </div>
            }
            {i++;}
        }
    </div>
    <a class="carousel-control-prev" href="#homeCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#homeCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="row pt-4">
    <div class="col-md-3">
        <div class="card">
            <h5 class="card-header">Cursos <span class="badge badge-warning">@Model.Registros[0]</span></h5>
            <div class="card-body">
                <p class="card-text">
                    Registro de Cursos para estudiantes.
                </p>
                <a href="@Url.Action("Index", "Curso")" class="btn btn-primary">Ver más</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <h5 class="card-header">Tutores <span class="badge badge-warning">@Model.Registros[1]</span></h5>
            <div class="card-body">
                <p class="card-text">
                    Registro de Padres de Familia de los estudiantes.
                </p>
                <a href="@Url.Action("Index", "Tutor")" class="btn btn-primary">Ver más</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <h5 class="card-header">Inscripciones <span class="badge badge-warning">@Model.Registros[2]</span></h5>
            <div class="card-body">
                <p class="card-text">
                    Modulo de Registro de Alumnos.
                </p>
                <a href="@Url.Action("Index", "Registro")" class="btn btn-primary">Ver más</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <h5 class="card-header">Alumnos <span class="badge badge-warning">@Model.Registros[3]</span></h5>
            <div class="card-body">
                <p class="card-text">
                    Registro de Alumnos al Sistema.
                </p>
                <a href="@Url.Action("Index", "Alumno")" class="btn btn-primary">Ver más</a>
            </div>
        </div>
    </div>
</div>