AppRegistroEstudiantes/Models/Registro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AppRegistroEstudiantes.Models
{
    public class Registro
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public decimal Beca { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Fecha de Inscripción")]
        public DateTime FechaInscripcion { get; set; }
        [DisplayName("Observacion 1")]
        public string Observacion1 { get; set; }
        [DisplayName("Observacion 2")]
        public string Observacion2 { get; set; }
        public bool EsTraspaso { get; set; }
        public bool EsBecado { get; set; }
        public bool EsRepitente { get; set; }
        [Required]
        public int Matricula { get; set; }
        public bool Estado { get; set; }

        public int AlumnoID { get; set; }
        public int CursoID { get; set; }

        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}

AppRegistroEstudiantes/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRegistroEstudiantes.Models;
using ClassLibraryFrontendUtils;
using PracticaWeb1.Context;

namespace AppRegistroEstudiantes.Controllers
{
    public class RegistroController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Registro
        public ActionResult Index()
        {
            var registro = db.Registro.Include(r => r.Alumno).Include(r => r.Curso);
            return View(registro.ToList());
        }

        // GET: Registro/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            return View(registro);
        }

        // GET: Registro/Create
        public ActionResult Create()
        {
            ViewBag.AlumnoID = new SelectList(db.Alumno, "Id", "NombreCompleto");
            ViewBag.CursoID = new SelectList(db.Curso, "Id", "Nombre");
            return View();
        }

        // POST: Registro/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FechaInscripcion,Observacion1,Observacion2,EsTraspaso,EsBecado,EsRepitente,Matricula,Estado,AlumnoID,CursoID")] Registro registro)
        {//en la vista para este metodo se estará enviando un form data
            string inputBeca = Request.Form["Beca"];
            registro.Beca = FrontendUtils.ParseDecimal(inputBeca);

            if (ModelState.IsValid)
            {
                db.Registro.Add(registro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AlumnoID = new SelectList(db.Alumno, "Id", "Nombre", registro.AlumnoID);
            ViewBag.CursoID = new SelectList(db.Curso, "Id", "Nombre", registro.CursoID);
            return View(registro);
        }

        // GET: Registro/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlumnoID = new SelectList(db.Alumno, "Id", "NombreCompleto", registro.AlumnoID);
            ViewBag.CursoID = new SelectList(db.Curso, "Id", "Nombre", registro.CursoID);
            return View(registro);
        }

        // POST: Registro/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FechaInscripcion,Observacion1,Observacion2,EsTraspaso,EsBecado,EsRepitente,Matricula,Estado,AlumnoID,CursoID")] Registro registro)
        {
            string inputBeca = Request.Form["Beca"];
            registro.Beca = FrontendUtils.ParseDecimal(inputBeca);

            if (ModelState.IsValid)
            {
                db.Entry(registro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AlumnoID = new SelectList(db.Alumno, "Id", "Nombre", registro.AlumnoID);
            ViewBag.CursoID = new SelectList(db.Curso, "Id", "Nombre", registro.CursoID);
            return View(registro);
        }

        // GET: Registro/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            return View(registro);
        }

        // POST: Registro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registro registro = db.Registro.Find(id);
            db.Registro.Remove(registro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppRegistroEstudiantes/Views/Registro/Create.cshtml
@model AppRegistroEstudiantes.Models.Registro

@{
    ViewBag.Title = "Registro - Nuevo";
}

<div class="form-horizontal" id="context">
    <h4>{{title}}</h4>
    <hr />
    <div class="card">
        <form action="@Url.Action("Create", "Registro")" method="post" @@submit="checkForm">
            @Html.AntiForgeryToken()
            <div class="card-header">
                @Html.ActionLink("Volver Atrás", "Index", "Registro", null, new { @class = "btn btn-secondary mr-1" })
                <input id="btnGuardar" type="submit" value="Guardar" class="btn btn-primary" />
            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.AlumnoID, "Alumno", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("AlumnoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AlumnoID, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.CursoID, "Curso", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("CursoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CursoID, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.FechaInscripcion, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Beca, htmlAttributes: new { @class = "control-label" })
                        <input class="form-control"
                               id="Beca"
                               min="0"
                               name="Beca"
                               step="0.01"
                               type="number"
                               v-model="Beca.value"
                               v-bind:disabled="Beca.disabled">
                        @Html.ValidationMessageFor(model => model.Beca, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Observacion1, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacion1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observacion1, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Observacion2, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacion2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observacion2, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsTraspaso, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsTraspaso)
                        @Html.ValidationMessageFor(model => model.EsTraspaso, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsBecado, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsBecado, new
                        {
                            htmlAttributes = new Dictionary<string, object> {
                            { "v-model", "esBecado" },
                            { "@change", "switchDisableInputBeca" },
                        }
                        })
                        @Html.ValidationMessageFor(model => model.EsBecado, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsRepitente, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsRepitente)
                        @Html.ValidationMessageFor(model => model.EsRepitente, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        <div>
                            @Html.CheckBox("Estado", true, new { @class = "check-box d-none" })
                            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        Vue.createApp({
            setup() {
                const title = 'Crear Nuevo Registro'; // no es reactivo
                const Beca = Vue.reactive({
                    value: 0,
                    disabled: true,
                });
                const esBecado = Vue.ref(false);
                const switchDisableInputBeca = () => {
                    Beca.disabled = !esBecado.value;
                    Beca.value = 0;
                };

                function checkForm(e) {
                    const form = new FormData();
                    form.append("__RequestVerificationToken", e.target["__RequestVerificationToken"].value);
                    form.append("AlumnoID", e.target["AlumnoID"].value);
                    form.append("CursoID", e.target["CursoID"].value);
                    form.append("FechaInscripcion", e.target["FechaInscripcion"].value);
                    form.append("Matricula", e.target["Matricula"].value);
                    form.append("Beca", Beca.value);
                    form.append("Observacion1", e.target["Observacion1"].value);
                    form.append("Observacion2", e.target["Observacion2"].value);
                    form.append("EsTraspaso", e.target["EsTraspaso"][0].checked);
                    form.append("EsBecado", esBecado.value);
                    form.append("EsRepitente", e.target["EsRepitente"][0].checked);
                    form.append("Estado", true);
                    fetch("/Registro/Create", {
                        method: "POST",
                        body: form
                    });
                    e.preventDefault();
                }
                return {
                    title,
                    Beca,
                    esBecado,
                    switchDisableInputBeca,
                    checkForm
                };
            }
        }).mount('#context');
    </script>
}

AppRegistroEstudiantes/Views/Registro/Delete.cshtml
@model AppRegistroEstudiantes.Models.Registro

@{
    ViewBag.Title = "Registro - Eliminar";
}

<div>
    <h4>¿Estas seguro que quieres eliminar el Registro con Id @Model.Id?</h4>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label class="h6">Alumno</label>
                <div>
                    @Html.DisplayFor(model => model.Alumno.NombreCompleto)
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Curso)</label>
                <div>
                    @Html.DisplayFor(model => model.Curso.Nombre)
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Matricula)</label>
                <div>
                    @Html.DisplayFor(model => model.Matricula)
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.FechaInscripcion)</label>
                <div>
                    @Html.DisplayFor(model => model.FechaInscripcion)
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Volver Atrás", "Index") |
            <input id="btnEliminar" type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    }
</div>

AppRegistroEstudiantes/Views/Registro/Details.cshtml
@model AppRegistroEstudiantes.Models.Registro

@{
    ViewBag.Title = "Registro - Detalles";
}

<div>
    <h4>Registro Id: @Model.Id</h4>
    <hr />
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Alumno.NombreCompleto)</label>
                <div>@Html.DisplayFor(model => model.Alumno.NombreCompleto)</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Curso)</label>
                <div>@Html.DisplayFor(model => model.Curso.Nombre)</div>
            </div>
        </div>
        <div class="col-md-1">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Beca)</label>
                <div>@Html.DisplayFor(model => model.Beca)</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.FechaInscripcion)</label>
                <div>@Html.DisplayFor(model => model.FechaInscripcion)</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Observacion1)</label>
                <div>@Html.DisplayFor(model => model.Observacion1)</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Observacion2)</label>
                <div>@Html.DisplayFor(model => model.Observacion2)</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.EsTraspaso)</label>
                <div>@(Model.EsTraspaso? "Si": "No")</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.EsBecado)</label>
                <div>@(Model.EsBecado ? "Si": "No")</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.EsRepitente)</label>
                <div>@(Model.EsRepitente ? "Si": "No")</div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label class="h6">@Html.DisplayNameFor(model => model.Matricula)</label>
                <div>@Html.DisplayFor(model => model.Matricula)</div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Volver Atrás", "Index") |
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
</p>

AppRegistroEstudiantes/Views/Registro/Edit.cshtml
@model AppRegistroEstudiantes.Models.Registro

@{
    ViewBag.Title = "Registro - Editar";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formEditRegistro" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" id="context">
        <h4>{{title}}</h4>
        <hr />
        <div class="card">
            <div class="card-header">
                @Html.ActionLink("Volver Atrás", "Index", "Registro", null, new { @class = "btn btn-secondary mr-1" })
                <input id="btnActualizar" type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.AlumnoID, "Alumno", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("AlumnoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AlumnoID, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.CursoID, "Curso", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("CursoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CursoID, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.FechaInscripcion, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control", @Value = Model.FechaInscripcion.ToString("yyyy-MM-dd") } })
                        @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.Beca, htmlAttributes: new { @class = "control-label" })
                        <input class="form-control"
                               id="Beca"
                               min="0"
                               name="Beca"
                               step="0.01"
                               type="number"
                               v-model="Beca.value"
                               v-bind:disabled="Beca.disabled">
                        @Html.ValidationMessageFor(model => model.Beca, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Observacion1, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacion1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observacion1, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Observacion2, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacion2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observacion2, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsTraspaso, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsTraspaso)
                        @Html.ValidationMessageFor(model => model.EsTraspaso, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsBecado, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsBecado, new
                        {
                            htmlAttributes = new Dictionary<string, object> {
                            { "v-model", "esBecado" },
                            { "@change", "switchDisableInputBeca" },
                        }
                        })
                        @Html.ValidationMessageFor(model => model.EsBecado, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @Html.LabelFor(model => model.EsRepitente, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EsRepitente)
                        @Html.ValidationMessageFor(model => model.EsRepitente, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-1 text-center">
                        @*@Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label" })*@
                        <div>
                            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "d-none" } })
                            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
        Vue.createApp({
            setup() {
                const title = 'Editar Registro';
                const Beca = Vue.reactive({
                    value: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.Beca,
Newtonsoft.Json.Formatting.Indented)),
                    disabled: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(!Model.EsBecado,
Newtonsoft.Json.Formatting.Indented)),
                });
                const esBecado = Vue.ref(@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.EsBecado,
Newtonsoft.Json.Formatting.Indented)));
                const switchDisableInputBeca = () => {
                    Beca.disabled = !esBecado.value;
                    Beca.value = 0;
                };
                return {
                    title,
                    Beca,
                    esBecado,
                    switchDisableInputBeca
                };
            }
        }).mount('#context');
</script>
}

AppRegistroEstudiantes/Views/Registro/Index.cshtml
@model IEnumerable<AppRegistroEstudiantes.Models.Registro>

@{
    ViewBag.Title = "Registro";
}

<h4>Lista de Registros</h4>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<div class="table-responsive" id="tablaRegistros">
    <table class="table">
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th width="15%">
                @Html.DisplayNameFor(model => model.Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInscripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacion1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacion2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="text-secondary" title="Editar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                        </svg>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", new { id = item.Id })" class="text-primary" title="Ver">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                        </svg>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="text-danger" title="Eliminar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Alumno.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Curso.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaInscripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Observacion1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Observacion2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Matricula)
                </td>
            </tr>
        }

    </table>
</div>